# Generated by Django 4.2.29 on 2026-03-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("outfits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outfit_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views_outfit",
                        to="outfits.outfitpost",
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views_reel",
                        to="reels.reel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outfit_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_outfit",
                        to="outfits.outfitpost",
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_reel",
                        to="reels.reel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="view",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("outfit_post__isnull", False), ("reel__isnull", True)),
                    models.Q(("outfit_post__isnull", True), ("reel__isnull", False)),
                    _connector="OR",
                ),
                name="view_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="view",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("outfit_post__isnull", False), ("user__isnull", False)
                ),
                fields=("user", "outfit_post"),
                name="uniq_user_outfit_view",
            ),
        ),
        migrations.AddConstraint(
            model_name="view",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reel__isnull", False), ("user__isnull", False)),
                fields=("user", "reel"),
                name="uniq_user_reel_view",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("outfit_post__isnull", False), ("reel__isnull", True)),
                    models.Q(("outfit_post__isnull", True), ("reel__isnull", False)),
                    _connector="OR",
                ),
                name="like_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outfit_post__isnull", False)),
                fields=("user", "outfit_post"),
                name="uniq_user_outfit_like",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reel__isnull", False)),
                fields=("user", "reel"),
                name="uniq_user_reel_like",
            ),
        ),
    ]
