# Generated by Django 4.2.29 on 2026-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0002_reel_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["created_at"], name="reels_reel_created_71ec95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["author", "created_at"], name="reels_reel_author__f29d9f_idx"
            ),
        ),
    ]
