# Generated by Django 4.2.29 on 2026-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
        ("outfits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="outfit_posts", to="recommendations.tag"
            ),
        ),
    ]
