# Generated by Django 4.2.29 on 2026-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outfits", "0002_outfitpost_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="outfitpost",
            index=models.Index(
                fields=["created_at"], name="outfits_out_created_d58b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outfitpost",
            index=models.Index(
                fields=["author", "created_at"], name="outfits_out_author__42f250_idx"
            ),
        ),
    ]
