# Generated by Django 4.2.29 on 2026-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outfits", "0003_outfitpost_outfits_out_created_d58b80_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitpost",
            name="boost_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outfitpost",
            name="is_boosted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outfitpost",
            name="shop_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="outfitpost",
            index=models.Index(
                fields=["is_boosted", "boost_expires_at"],
                name="outfits_out_is_boos_9e76ef_idx",
            ),
        ),
    ]
