# Generated by Django 4.2.29 on 2026-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["outfit_post", "created_at"],
                name="comments_co_outfit__d1bdaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["reel", "created_at"], name="comments_co_reel_id_5532ec_idx"
            ),
        ),
    ]
